name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you would like to see.
      placeholder: I would like to see...
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Is this related to a problem?
      description: Is this feature request related to a problem?
      placeholder: I'm always frustrated when...
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe alternatives you've considered
      placeholder: I've tried to accomplish this by...
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request